import {
  Wallet,
  Landmark,
  Banknote,
  Receipt,
  Coins,
  CreditCard,
  PiggyBank,
  Building,
  Briefcase,
  Users,
  User,
  BarChart3,
  PieChart,
  TrendingUp,
  Settings,
  Database,
  FileText,
  Folder,
  Grid2x2,
  LayoutDashboard,
  Boxes,
} from "lucide-react";

export const iconOptions = [
  { name: "Wallet", icon: Wallet },
  { name: "Landmark", icon: Landmark },
  { name: "Banknote", icon: Banknote },
  { name: "Receipt", icon: Receipt },
  { name: "Coins", icon: Coins },
  { name: "CreditCard", icon: CreditCard },
  { name: "PiggyBank", icon: PiggyBank },
  { name: "Building", icon: Building },
  { name: "Briefcase", icon: Briefcase },
  { name: "Users", icon: Users },
  { name: "User", icon: User },
  { name: "BarChart3", icon: BarChart3 },
  { name: "PieChart", icon: PieChart },
  { name: "TrendingUp", icon: TrendingUp },
  { name: "Settings", icon: Settings },
  { name: "Database", icon: Database },
  { name: "FileText", icon: FileText },
  { name: "Folder", icon: Folder },
  { name: "Grid2x2", icon: Grid2x2 },
  { name: "LayoutDashboard", icon: LayoutDashboard },
  { name: "Boxes", icon: Boxes },
];