"use client";

import { X } from "lucide-react";

import axios from "axios";
import { useEffect, useState } from "react";

type Props = {
  open: boolean;
  ratId: string | null;
  onClose: () => void;
};

export default function RATDetailsModal({
  open,
  ratId,
  onClose,
}: Props) {

  const [loading, setLoading] =
    useState(false);

  const [header, setHeader] =
    useState<any>(null);

  const [items, setItems] =
    useState<any[]>([]);


  useEffect(() => {

  if (
    open &&
    ratId
  ) {

    loadRAT();

  }

}, [open, ratId]);

async function loadRAT() {

  try {

    setLoading(true);

    const res =
      await axios.get(
        `/api/rat/${ratId}`
      );

    setHeader(
      res.data.header
    );

    setItems(
      res.data.items ?? []
    );

  } catch (err) {

    console.error(err);

  } finally {

    setLoading(false);

  }

}

  if (!open) return null;

  return (

    <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/40 p-6">

      <div className="w-full max-w-7xl overflow-hidden rounded-xl bg-white shadow-2xl">

        {/* Header */}

        <div className="flex items-center justify-between border-b bg-slate-50 px-6 py-4">

          <div>

            <h2 className="text-xl font-bold text-slate-800">

              RAT Details

            </h2>

            <p className="text-sm text-slate-500">

              Registered Accountable Forms Transaction

            </p>

          </div>

          <button
            onClick={onClose}
            className="rounded-lg p-2 hover:bg-slate-200"
          >

            <X size={22} />

          </button>

        </div>

        {/* Content */}

        <div className="p-6">

          {loading ? (

              <div className="py-16 text-center text-slate-500">

                  Loading RAT...

              </div>

          ) : (

              <div className="space-y-6">

                  {/* Header Information */}

                  <div className="grid grid-cols-2 gap-6 rounded-lg border p-5">

                      <div>

                          <div className="text-xs uppercase text-slate-500">

                              RAT Number

                          </div>

                          <div className="font-semibold text-blue-700">

                              {header?.rat_no}

                          </div>

                      </div>

                      <div>

                          <div className="text-xs uppercase text-slate-500">

                              RIS Number

                          </div>

                          <div>

                              {header?.ris_no}

                          </div>

                      </div>

                      <div>

                          <div className="text-xs uppercase text-slate-500">

                              Accountable Officer

                          </div>

                          <div>

                              {header?.accountable_officer}

                          </div>

                      </div>

                      <div>

                          <div className="text-xs uppercase text-slate-500">

                              Generated By

                          </div>

                          <div>

                              {header?.generated_by_name}

                          </div>

                      </div>

                      <div>

                          <div className="text-xs uppercase text-slate-500">

                              Generated Date

                          </div>

                          <div>

                              {header?.generated_at
                                  ? new Date(
                                        header.generated_at
                                    ).toLocaleString()
                                  : "-"}

                          </div>

                      </div>

                      <div>

                          <div className="text-xs uppercase text-slate-500">

                              Status

                          </div>

                          <span className="rounded-full bg-green-100 px-3 py-1 text-xs font-semibold text-green-700">

                              {header?.status}

                          </span>

                      </div>

                  </div>

                  {/* Assigned Booklets */}

                  <div className="rounded-lg border">

                      <div className="border-b bg-slate-50 px-5 py-3 font-semibold">

                          Assigned Booklets

                      </div>

                      <div className="overflow-x-auto">

                          <table className="w-full">

                              <thead className="bg-slate-100">

                                  <tr>

                                      <th className="px-4 py-3 text-left">

                                          Form

                                      </th>

                                      <th className="px-4 py-3 text-left">

                                          Control No.

                                      </th>

                                      <th className="px-4 py-3">

                                          Series

                                      </th>

                                      <th className="px-4 py-3">

                                          OR Range

                                      </th>

                                      <th className="px-4 py-3">

                                          Current OR

                                      </th>

                                  </tr>

                              </thead>

                              <tbody>

                                  {items.map((item) => (

                                      <tr
                                          key={item.id}
                                          className="border-b"
                                      >

                                          <td className="px-4 py-3">

                                              {item.form_code}

                                          </td>

                                          <td className="px-4 py-3">

                                              {item.control_no}

                                          </td>

                                          <td className="px-4 py-3">

                                              {item.series}

                                          </td>

                                          <td className="px-4 py-3">

                                              {item.beginning_or}
                                              {" - "}
                                              {item.ending_or}

                                          </td>

                                          <td className="px-4 py-3">

                                              {item.current_or}

                                          </td>

                                      </tr>

                                  ))}

                              </tbody>

                          </table>

                      </div>

                  </div>

              </div>

          )}

      </div>

      </div>

    </div>

  );

}