"use client";

import { X } from "lucide-react";
import axios from "axios";
import { useEffect, useState } from "react";

type Props = {
  open: boolean;
  ratId: string | null;
  onClose: () => void;
};

export default function RATDetailsModal({
  open,
  ratId,
  onClose,
}: Props) {
  const [loading, setLoading] = useState(false);
  const [header, setHeader] = useState<any>(null);
  const [items, setItems] = useState<any[]>([]);

  useEffect(() => {
    if (!open || !ratId) {
      return;
    }

    loadRAT();
  }, [open, ratId]);

  async function loadRAT() {
    if (!ratId) {
      return;
    }

    try {
      setLoading(true);

      const response = await axios.get(
        `/api/rat/${ratId}`
      );

      setHeader(
        response.data?.header ?? null
      );

      setItems(
        Array.isArray(response.data?.items)
          ? response.data.items
          : []
      );
    } catch (error) {
      console.error(
        "Failed to load RAT:",
        error
      );

      setHeader(null);
      setItems([]);
    } finally {
      setLoading(false);
    }
  }

  if (!open) {
    return null;
  }

  return (
    <div
      className="fixed inset-0 z-[80] flex items-center justify-center bg-black/40 p-4"
      onClick={onClose}
    >
      <div
        className="w-full max-w-4xl overflow-hidden rounded-xl bg-white shadow-2xl"
        onClick={(event) => {
          event.stopPropagation();
        }}
      >
        {/* Header */}

        <div className="flex items-center justify-between border-b bg-slate-50 px-5 py-3">
          <div>
            <h2 className="text-lg font-bold text-slate-800">
              RAT Details
            </h2>

            <p className="text-xs text-slate-500">
              Registered Accountable Forms Transaction
            </p>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-1.5 transition hover:bg-slate-200"
            title="Close"
            aria-label="Close"
          >
            <X size={20} />
          </button>
        </div>

        {/* Content */}

        <div className="max-h-[75vh] overflow-y-auto p-5">
          {loading && (
            <div className="py-12 text-center text-sm text-slate-500">
              Loading RAT...
            </div>
          )}

          {!loading && !header && (
            <div className="py-12 text-center text-sm text-slate-500">
              RAT information not found.
            </div>
          )}

          {!loading && header && (
            <div className="space-y-4">

              {/* RAT Information */}

              <div className="rounded-lg border bg-slate-50 p-4">
                <div className="grid grid-cols-2 gap-x-8 gap-y-3 md:grid-cols-4">

                  <div>
                    <div className="text-[10px] font-semibold uppercase text-slate-500">
                      RAT Number
                    </div>

                    <div className="mt-0.5 text-sm font-bold text-blue-700">
                      {header.rat_no ?? "-"}
                    </div>
                  </div>

                  <div>
                    <div className="text-[10px] font-semibold uppercase text-slate-500">
                      RIS Number
                    </div>

                    <div className="mt-0.5 text-sm font-medium text-slate-700">
                      {header.ris_no ?? "-"}
                    </div>
                  </div>

                  <div>
                    <div className="text-[10px] font-semibold uppercase text-slate-500">
                      Accountable Officer
                    </div>

                    <div className="mt-0.5 text-sm font-semibold text-slate-800">
                      {header.accountable_officer ?? "-"}
                    </div>
                  </div>

                  <div>
                    <div className="text-[10px] font-semibold uppercase text-slate-500">
                      Status
                    </div>

                    <div className="mt-0.5">
                      <span className="inline-flex rounded-full bg-green-100 px-2.5 py-1 text-[10px] font-bold text-green-700">
                        {header.status ?? "-"}
                      </span>
                    </div>
                  </div>

                  <div>
                    <div className="text-[10px] font-semibold uppercase text-slate-500">
                      Generated By
                    </div>

                    <div className="mt-0.5 text-sm text-slate-700">
                      {header.generated_by_name ?? "-"}
                    </div>
                  </div>

                  <div>
                    <div className="text-[10px] font-semibold uppercase text-slate-500">
                      Generated Date
                    </div>

                    <div className="mt-0.5 text-sm text-slate-700">
                      {header.generated_at
                        ? new Date(
                            header.generated_at
                          ).toLocaleString()
                        : "-"}
                    </div>
                  </div>

                  <div>
                    <div className="text-[10px] font-semibold uppercase text-slate-500">
                      Booklets
                    </div>

                    <div className="mt-0.5 text-sm font-bold text-slate-800">
                      {items.length}
                    </div>
                  </div>

                </div>
              </div>

              {/* Assigned Accountable Forms */}

              <div className="rounded-lg border">
                <div className="border-b bg-slate-50 px-4 py-2.5">
                  <h3 className="text-sm font-semibold text-slate-800">
                    Assigned Accountable Forms
                  </h3>

                  <p className="text-[11px] text-slate-500">
                    Booklets assigned through this RAT
                  </p>
                </div>

                <div className="overflow-x-auto">
                  <table className="w-full text-sm">

                    <thead className="bg-slate-100">
                      <tr className="text-xs font-semibold text-slate-600">

                        <th className="px-3 py-2 text-left">
                          Form
                        </th>

                        <th className="px-3 py-2 text-left">
                          Control No.
                        </th>

                        <th className="px-3 py-2 text-center">
                          Series
                        </th>

                        <th className="px-3 py-2 text-center">
                          OR Range
                        </th>

                        <th className="px-3 py-2 text-center">
                          Current OR
                        </th>

                      </tr>
                    </thead>

                    <tbody>
                      {items.length === 0 ? (
                        <tr>
                          <td
                            colSpan={5}
                            className="px-4 py-8 text-center text-xs text-slate-500"
                          >
                            No assigned booklets.
                          </td>
                        </tr>
                      ) : (
                        items.map((item) => (
                          <tr
                            key={item.id}
                            className="border-t"
                          >
                            <td className="px-3 py-2.5 font-semibold text-slate-800">
                              {item.form_code ?? "-"}
                            </td>

                            <td className="px-3 py-2.5 text-slate-700">
                              {item.control_no ?? "-"}
                            </td>

                            <td className="px-3 py-2.5 text-center text-slate-700">
                              {item.series ?? "-"}
                            </td>

                            <td className="px-3 py-2.5 text-center text-slate-700">
                              {item.beginning_or ?? "-"}
                              {" - "}
                              {item.ending_or ?? "-"}
                            </td>

                            <td className="px-3 py-2.5 text-center font-semibold text-slate-800">
                              {item.current_or ?? "-"}
                            </td>
                          </tr>
                        ))
                      )}
                    </tbody>

                  </table>
                </div>
              </div>

              {/* Remarks */}

              {header.remarks && (
                <div className="rounded-lg border bg-slate-50 px-4 py-3">
                  <div className="text-[10px] font-semibold uppercase text-slate-500">
                    Remarks
                  </div>

                  <div className="mt-1 text-sm text-slate-700">
                    {header.remarks}
                  </div>
                </div>
              )}

            </div>
          )}
        </div>

      </div>
    </div>
  );
}